# https://spring.pleiades.io/spring-boot/docs/current/reference/html/application-properties.html
management:
  endpoint:
    health:
      enabled: false
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful # default lifecycle 30s

helloworld:
  text: my best friend
---
management:
  endpoint:
    health:
      enabled: true
spring:
  config:
    activate:
      on-profile: dev
helloworld:
  text: my friend
