name: ci

on: [push, pull_request]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Static code analysis
        run: ./gradlew detekt
